version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken by default from the ".env" file defined like: 
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi for instance.

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port
    # volumes: 
      # - ./database/mssql:/var/opt/mssql

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  mariadb:
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - '3306:3306'
    # volumes:
    #   - ./database/mariadb_data:/bitnami

  moodle:
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5150:80'
      - '443:443'
    # volumes:
    #   - ./database/moodle_data:/bitnami

  # elk:
  #   environment:
  #     - MAX_MAP_COUNT=262144
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   volumes:
  #     - ./database/elk-data:/var/lib/elasticsearch

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  proxy:
    environment:
      - ENABLE_SSL=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    command: [nginx-debug, '-g', 'daemon off;']

  brandedtemplates.api:
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5101
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=BRANDED_TEMPLATES;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5101:80"  
    volumes: 
      - ./ssl:${SSL_PATH} 

  careerdays.api:
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5102
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=CAREER_DAYS;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5102:80" 
    volumes: 
      - ./ssl:${SSL_PATH}

  educationalinstitutions.api:
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5103
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=EDUCATIONAL_INSTITUTIONS;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5103:80"  
    volumes: 
      - ./ssl:${SSL_PATH}

  employers.api:
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5104
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=EMPLOYERS;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5104:80"  
    volumes: 
      - ./ssl:${SSL_PATH}

  login.api:
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5105
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=LOGIN;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
      - SymmetricKey=kAkoYto_yeb!chesk!y_k1uch
      - IdentityServiceUrl=http://localhost:5105/
      - WebAppClient=http://${EXTERNAL_DNS_NAME_OR_IP}:{FRONTEND_PORT}/auth/
    ports:
      - "5105:80"  
    volumes: 
      # - ./src/Services/Domain/Login/Login.API/Certificates:/app/Certificates
      - ./ssl:${SSL_PATH}

  paidservices.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5106
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=PAID_SERVICES;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5106:80"  
    volumes: 
      - ./ssl:${SSL_PATH}

  resumes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5107
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=RESUMES;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5107:80" 
    volumes: 
      - ./ssl:${SSL_PATH}

  vacancies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5108
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=VACANCIES;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5108:80" 
    volumes: 
      - ./ssl:${SSL_PATH}

  dictionaries.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5109
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ConnectionString=Server=sql.data;Database=DICTIONARIES;User Id=sa;Password=Pass@word
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5109:80" 
    volumes:
      - ./src/Services/Integration/Dictionaries/Dictionaries.API/Sources:/app/Sources 
      - ./ssl:${SSL_PATH}

  moodle.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5111
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - MoodleRestUrl=moodle/webservice/rest/server.php
      - MoodleToken=f3f5be086fd0b9cf4ed3d09a3fdf1da0
      - MoodleRestFormat=json
      - Seq=http://seq
    ports:
      - "5111:80" 
    volumes: 
      - ./ssl:${SSL_PATH}

  emailnotifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5110
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - CorsPolicy=${CORS_POLICY}
      - EventBusRetryCount=${EVENT_BUS_RETRY_COUNT}
      - EventBusConnection=rabbitmq
      - EventBusUserName=${EVENT_BUS_USER_NAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5110:80" 
    volumes: 
      - ./ssl:${SSL_PATH}

  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=5200
      - Kestrel__Certificates__Default__Path=${SSL_PATH}/${SSL_CERT_NAME}
      - Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - CorsPolicy=${CORS_POLICY}
      - IdentityUrl=http://login.api
      - ElasticSearch=elk:9200
      - Seq=http://seq
    ports:
      - "5200:80"   
    volumes:
      - ./src/ApiGateways/WebApp.Bff/apigw:${OCELOT_VOLUME_SPEC:-/app/configuration}
      - ./ssl:${SSL_PATH}