version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  mariadb:
    image: 'bitnami/mariadb:latest'

  moodle:
    image: 'bitnami/moodle:latest'
    depends_on:
      - mariadb

  # elk:
  #   image: sebp/elk

  seq:
    image: datalust/seq:latest

  proxy:
    image: nginx:latest
    depends_on:
      - apigw

  brandedtemplates.api:
    image: jobobserver/brandedtemplates.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/BrandedTemplates/BrandedTemplates.API/Dockerfile    
    depends_on:
      - sql.data
      - seq
  #     - elk

  careerdays.api:
    image: jobobserver/careerdays.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/CareerDays/CareerDays.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  educationalinstitutions.api:
    image: jobobserver/educationalinstitutions.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/EducationalInstitutions/EducationalInstitutions.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  employers.api:
    image: jobobserver/employers.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/Employers/Employers.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  login.api:
    image: jobobserver/login.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/Login/Login.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  paidservices.api:
    image: jobobserver/paidservices.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/PaidServices/PaidServices.API/Dockerfile    
    depends_on:
      - sql.data
      - seq
  #     - elk

  resumes.api:
    image: jobobserver/resumes.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/Resumes/Resumes.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  vacancies.api:
    image: jobobserver/vacancies.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/Vacancies/Vacancies.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
  #     - elk

  dictionaries.api:
    image: jobobserver/dictionaries.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Integration/Dictionaries/Dictionaries.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - seq
      # - elk

  moodle.api:
    image: jobobserver/moodle.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Integration/Moodle/Moodle.API/Dockerfile    
    depends_on:
      - rabbitmq
      - seq
      # - elk

  emailnotifications.api:
    image: jobobserver/emailnotifications.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Technical/EmailNotifications/EmailNotifications.API/Dockerfile    
    depends_on:
      - rabbitmq
      - seq
  #     - elk

  apigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
      - brandedtemplates.api
      - careerdays.api
      - educationalinstitutions.api
      - employers.api
      - login.api
      - paidservices.api
      - resumes.api
      - vacancies.api
      - dictionaries.api
      - moodle.api
      - seq
      # - elk