version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  # mariadb:
  #   image: 'bitnami/mariadb:latest'

  # moodle:
  #   image: 'bitnami/moodle:latest'
  #   depends_on:
  #     - mariadb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.2.4
  #   depends_on:
  #     - elasticsearch

  # brandedtemplates.api:
  #   image: jobobserver/brandedtemplates.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/BrandedTemplates/BrandedTemplates.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - elasticsearch

  # careerdays.api:
  #   image: jobobserver/careerdays.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/CareerDays/CareerDays.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  # educationalinstitutions.api:
  #   image: jobobserver/educationalinstitutions.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/EducationalInstitutions/EducationalInstitutions.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  # employers.api:
  #   image: jobobserver/employers.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/Employers/Employers.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  # login.api:
  #   image: jobobserver/login.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/Login/Login.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  # paidservices.api:
  #   image: jobobserver/paidservices.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/PaidServices/PaidServices.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - elasticsearch

  # resumes.api:
  #   image: jobobserver/resumes.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Domain/Resumes/Resumes.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  vacancies.api:
    image: jobobserver/vacancies.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Domain/Vacancies/Vacancies.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq
      - elasticsearch

  # dictionaries.api:
  #   image: jobobserver/dictionaries.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Integration/Dictionaries/Dictionaries.API/Dockerfile    
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - elasticsearch

  #   emailnotifications.api:
  #   image: jobobserver/dictionaries.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Services/Technical/EmailNotifications/EmailNotifications.API/Dockerfile    
  #   depends_on:
  #     - rabbitmq
  #     - elasticsearch

  # apigw:
  #   image: eshop/ocelotapigw:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/ApiGateways/ApiGateway/Dockerfile
  #   depends_on:
  #     - sql.data
  #     - rabbitmq
  #     - brandedtemplates.api
  #     - careerdays.api
  #     - educationalinstitutions.api
  #     - employers.api
  #     - login.api
  #     - paidservices.api
  #     - resumes.api
  #     - vacancies.api
  #     - dictionaries.api
  #     - elasticsearch